In [10]:
dataPath = '../../Data/Snopes'
lgFeaturesPath = '../Data/linguistic features'
import os
import json

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = 'english', \
                             max_features = 5000) 

train_data_features = vectorizer.fit_transform(['I love you', 'you you'])
train_data_features = train_data_features.toarray()
print (train_data_features)

ModuleNotFoundError: No module named 'sklearn'

In [16]:
data = []
for filePath in os.listdir(dataPath):
    if filePath.endswith('.json'):
        file = open(os.path.join(dataPath, filePath), 'r')
        data.append(json.load(file))
        break
print (data)

[{'Origins': 'In August 2015, a survey scam promising customers $100 off "Back to School" coupons for the Meijer hypermarket chain began circulating online: The $100 Meijer coupon scam is very similar to other schemes aimed at defrauding the customers of Target, Publix, Kroger, and Home Depot, all of which redirect users to a web site where they are asked to like, share, and/or comment on the coupons, ensuring that the scams get passed around social media:', 'Fact Check': 'Is Meijer offering $100 off "Back to School" coupons?', 'Description': "While each of these scams feature slight variations, they typically redirect users to survey sites where they are asked to provide personal information such as e-mail addresses, telephone numbers, dates of birth, and credit card numbers. The Better Business Bureau offers these three tips to identify scams on Facebook: Don't believe what you see. It's easy to steal the colors, logos and header of an established organization. Scammers can also make

In [2]:
import numpy as np
snippets = np.array([[0,1,2],[3,4,5],[6,7,8]])
idx = [0,2]
snippets[idx]

array([[0, 1, 2],
       [6, 7, 8]])

References
https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/

In [ ]:
%%time
%run main.py

In [18]:
import re
def extractSnippets(article):
    snippets = []
    snippetMarkNumbers = []	#list of list, inner list records number of ! ? ""
    NSS = 4 # number of a snippet in a sentence
    #articleSentences = re.split(r'[.|!|?]', article)
    articleSentences = []
    articleSentencesWithMarks = []
    sentence = ''
    for c in article:
    	if c not in ['?', '!', '.']:
    		sentence += c
    	else:
    		articleSentences.append(sentence)
    		if c in ['?', '!']:
    			sentence += c
    		else:
    			sentence += ' '
    		articleSentencesWithMarks.append(sentence)
    		sentence = ''
    # print(articleSentences)
    # no stripped kinda needed: like $100, "bill", these are critical
    # but vocab from the vectorizer is without these 
    for i in range(len(articleSentences)):
    	articleSentences[i] = " ".join(re.findall("[a-zA-Z0-9]+", articleSentences[i])) + ' '
    # print(articleSentences)
    while '' in articleSentences:
        articleSentences.remove('')
    while '' in articleSentencesWithMarks:
        articleSentencesWithMarks.remove('')
    for i in range(len(articleSentences) - NSS + 1):
        temp = articleSentences[i : i+NSS]
        snippet = ""
        for j in range(NSS):
            snippet = snippet + temp[j]
        snippets.append(snippet)

        snippetMarkNumber = [0,0,0]
        for j in range(NSS):
        	curSentence = articleSentencesWithMarks[i+j]
        	if '!' in curSentence:
        		snippetMarkNumber[0] = 1
        	if '?' in curSentence:
        		snippetMarkNumber[1] = 1
        	if '"' in curSentence:
        		snippetMarkNumber[2] = 1

        snippetMarkNumbers.append(snippetMarkNumber)

    return snippets, snippetMarkNumbers

"She had all the typical symptoms of a pregnant woman. It s not the first time a young woman falls pregnant without the consent of her parents, but the girl seemed sincere when she said she had never had sexual relations with a boy, and she urged me to check her hymen, which I eventually did, and to my utter surprise, the hymen was fully intact. It is impossible she has been impregnated by male sperm she assures. In my 26 years of practice, I have never heard once of such a thing as someone being impregnated by a vaccine, but I did some research and found out it is more common than most people think . The claim cleverly layered the suggestion of a falsehood within its own fabrication to facilitate the spread of the story; by that sleight of hand, readers surmised the girl had lied about her sexual experience and had blamed the flu vaccine to deflect suspicion about the true nature of her pregnancy. None of this (neither the girl's claims nor the article reporting them) was true, however. World News Daily Report is just one of many fake news sites that print fictitious articles, as noted in their disclaimer: WNDR assumes however all responsibility for the satirical nature of its articles and for the fictional nature of their content. All characters appearing in the articles in this website even those based on real people are entirely fictional and any resemblance between them and any persons, living, dead, or undead is purely a miracle. World News Daily Report previously spread fake news stories about loggers accidentally cutting down the world's largest tree, Yoko Ono's admitting to an affair with Hillary Clinton, and a 179-year-old man living in India. Last updated: 5 October 2015")

In [20]:
snippets, snippetMarkNumbers = extractSnippets("She had all the \"typical symptoms\" of a pregnant woman. It s not the first time a young woman falls pregnant without the consent of her parents, but the girl seemed sincere when she said she had never had sexual relations with a boy, and she urged me to check her hymen, which I eventually did, and to my utter surprise, the hymen was fully intact! It is impossible she has been impregnated by male sperm she assures. In my 26 years of practice, I have never heard once of such a thing as someone being impregnated by a vaccine, but I did some research and found out it is more common than most people think . The claim cleverly layered the suggestion of a falsehood within its own fabrication to facilitate the spread of the story; by that sleight of hand, readers surmised the girl had lied about her sexual experience and had blamed the flu vaccine to deflect suspicion about the true nature of her pregnancy. None of this (neither the girl's claims nor the article reporting them) was true, however. World News Daily Report is just one of many fake news sites that print fictitious articles, as noted in their disclaimer: WNDR assumes however all responsibility for the satirical nature of its articles and for the fictional nature of their content. All characters appearing in the articles in this website even those based on real people are entirely fictional and any resemblance between them and any persons, living, dead, or undead is purely a miracle. World News Daily Report previously spread fake news stories about loggers accidentally cutting down the world's largest tree, Yoko Ono's admitting to an affair with Hillary Clinton, and a 179-year-old man living in India. Last updated: 5 October 2015")

In [25]:
print (snippetMarkNumbers)
[snippetMarkNumbers[i] for i in [1,2,4]]

[[1, 0, 1], [1, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


[[1, 0, 0], [0, 0, 0], [0, 0, 0]]

In [39]:
import numpy as np
gan = np.array(snippetMarkNumbers)
print(gan.shape)
a = np.random.rand(gan.shape[0], 22)
print(a.shape)
print (a)
# np.concatenate((a, gan.T))
np.concatenate((a, gan), axis=1) 

(6, 3)
(6, 22)
[[ 0.52255729  0.77166684  0.91972238  0.76387004  0.77065855  0.54262949
   0.9222469   0.27679233  0.99768112  0.89313645  0.43076568  0.7177737
   0.2764045   0.08639618  0.41921079  0.63650602  0.86776222  0.0117781
   0.18707721  0.08995423  0.07817988  0.07866437]
 [ 0.76178652  0.90175367  0.06259302  0.10785361  0.37860143  0.6633708
   0.8743326   0.40203509  0.07515205  0.5306684   0.91111047  0.59152873
   0.08796942  0.45502329  0.21374881  0.19013419  0.57725255  0.55862745
   0.15008388  0.15447845  0.36770738  0.1768495 ]
 [ 0.71936969  0.65055979  0.97672776  0.31259422  0.57212344  0.92712656
   0.74485415  0.35221219  0.69823947  0.8368633   0.29837189  0.0135564
   0.62595401  0.7747816   0.36223205  0.35492041  0.53603673  0.90367703
   0.48764274  0.7135271   0.35616759  0.44944659]
 [ 0.38204493  0.93292068  0.33110297  0.942626    0.99324169  0.46911891
   0.10581965  0.37631415  0.97997687  0.46888353  0.31754888  0.06692676
   0.54261545  0.86670

array([[ 0.52255729,  0.77166684,  0.91972238,  0.76387004,  0.77065855,
         0.54262949,  0.9222469 ,  0.27679233,  0.99768112,  0.89313645,
         0.43076568,  0.7177737 ,  0.2764045 ,  0.08639618,  0.41921079,
         0.63650602,  0.86776222,  0.0117781 ,  0.18707721,  0.08995423,
         0.07817988,  0.07866437,  1.        ,  0.        ,  1.        ],
       [ 0.76178652,  0.90175367,  0.06259302,  0.10785361,  0.37860143,
         0.6633708 ,  0.8743326 ,  0.40203509,  0.07515205,  0.5306684 ,
         0.91111047,  0.59152873,  0.08796942,  0.45502329,  0.21374881,
         0.19013419,  0.57725255,  0.55862745,  0.15008388,  0.15447845,
         0.36770738,  0.1768495 ,  1.        ,  0.        ,  0.        ],
       [ 0.71936969,  0.65055979,  0.97672776,  0.31259422,  0.57212344,
         0.92712656,  0.74485415,  0.35221219,  0.69823947,  0.8368633 ,
         0.29837189,  0.0135564 ,  0.62595401,  0.7747816 ,  0.36223205,
         0.35492041,  0.53603673,  0.90367703,  0

In [37]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])